### ISSUE TITLE
THE BIG PROBLEM

### ISSUE THREAD

**Issue by double-beep** [helper-beep/batch#14]
SYNC WITH MASTER.
Hello, @helper-beep you are always out of date and the new pull requests do not help.
You can commit to your repository and in the description simply write:
`Co-authored by: @<name> <email>`
Thanks!

**Comment by double-beep** [comment]
I have opened a pull request in the following link.

**Comment by helper-beep** [comment]
Sorry, you are right, I will add the commit. 👎

**Comment by helper-beep** [comment]
Solved, closing.

**Comment by double-beep** [comment]
And closing via ...
